# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dkmr <- function(x, a, b) {
    .Call('team10stats799_dkmr', PACKAGE = 'team10stats799', x, a, b)
}

pkmr <- function(q, a, b) {
    .Call('team10stats799_pkmr', PACKAGE = 'team10stats799', q, a, b)
}

qkmr <- function(p, a, b) {
    .Call('team10stats799_qkmr', PACKAGE = 'team10stats799', p, a, b)
}

